### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [88]:
def swp(metrix):
    metrix[[0,-1],:] = metrix[[-1,0],:]

    return metrix

In [89]:
import numpy as np
a = np.empty((5,5))
for i in range(5):
  for j in range(5):
      a[i, j] = np.random.randint(0, 10)

print(a)
swp(a)
        

[[6. 9. 0. 9. 3.]
 [8. 4. 0. 7. 9.]
 [8. 3. 6. 5. 0.]
 [2. 8. 4. 5. 9.]
 [5. 3. 6. 1. 1.]]


array([[5., 3., 6., 1., 1.],
       [8., 4., 0., 7., 9.],
       [8., 3., 6., 5., 0.],
       [2., 8., 4., 5., 9.],
       [6., 9., 0., 9., 3.]])

## Builtin function

In [90]:
m = np.random.randint(1,26,(5,5))
print(m)
swp(m)



[[16 25 19 10 21]
 [23  7  9 25 14]
 [ 5 17 14 10 24]
 [12  5 18 15  8]
 [18  3 20  5  4]]


array([[18,  3, 20,  5,  4],
       [23,  7,  9, 25, 14],
       [ 5, 17, 14, 10, 24],
       [12,  5, 18, 15,  8],
       [16, 25, 19, 10, 21]])

### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [91]:
def remove_zerorows(arr):
    new_arr = []
    for row in arr:
        if not any(x == 0 for x in row):
            new_arr.append(row)

    return new_arr


arr = [[1, 2, 3, 0], [1, 2, 3, 4], [1, 2, 0, 4],[1, 2, 9, 4],[1, 0, 9, 4]]
remove_zerorows(arr)


[[1, 2, 3, 4], [1, 2, 9, 4]]

### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [105]:
arr = [1.00000000+0.j, 0.70710678+0.70710678j]
print(f" Real Part {np.real(arr)} , and Imaginary part {np.imag(arr)}")

 Real Part [1.         0.70710678] , and Imaginary part [0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [93]:
def removeduplicate(arr):
    b = []
    for x in a:
        if x not in b:
            b.append(x)
    return b

a = [1, 1, 2, 3, 4, 5, 5, 6, 7, 7, 8]
removeduplicate(a)

[1, 2, 3, 4, 5, 6, 7, 8]

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [94]:
import numpy as np
a = np.empty((3, 3, 3))
for i in range(3):
  for j in range(3):
    for k in range(3):
      a[i, j, k] = np.random.randint(0, 10)
print(a)

[[[4. 4. 6.]
  [3. 3. 6.]
  [6. 1. 4.]]

 [[3. 4. 1.]
  [9. 7. 9.]
  [8. 4. 5.]]

 [[0. 6. 3.]
  [7. 9. 1.]
  [1. 3. 6.]]]


## Builtin function

In [95]:
np.random.random((3,3,3))

array([[[0.47022999, 0.69278234, 0.70616768],
        [0.93677409, 0.87441116, 0.19653094],
        [0.80579199, 0.39407551, 0.85028633]],

       [[0.13506745, 0.21116749, 0.38657745],
        [0.89092976, 0.34295156, 0.27008698],
        [0.7430208 , 0.0525084 , 0.975101  ]],

       [[0.44904035, 0.60855974, 0.02233924],
        [0.53296157, 0.84712703, 0.04919377],
        [0.5968618 , 0.33141904, 0.3623236 ]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [96]:
def sort(lis):
    for i in range(0, len(lis)):
        for j in range(i+1, len(lis)):
            if lis[i] >= lis[j]:
                lis[i], lis[j] = lis[j],lis[i]
    return lis

arr=np.random.randint(0, 50, 10)
print("Original List:", arr)
l = sort(arr)
print("Sorted List", l)

Original List: [ 1 23 18 48 39 37  6  4 30 24]
Sorted List [ 1  4  6 18 23 24 30 37 39 48]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [97]:
a = np.random.random((10))
b = np.random.random((10))

for i in range(len(a)):
 
    if a[i] != b[i]:
         print("equal")
    else:
        print("Not Equal")



equal
equal
equal
equal
equal
equal
equal
equal
equal
equal


In [98]:
a = np.random.random((10))
b = np.random.random((10))
if np.allclose(a, b) == True:
    print("Both List is Equal")
else:
    print("Both List is Not Equal")

Both List is Not Equal


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [99]:
array =np.array([[10, 40],
                 [30, 20]])

np.sort(array, axis=0)

array([[10, 20],
       [30, 40]])

### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [100]:
arr = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.])


print('Original array:', arr)
print('Floor:', np.floor(arr))
print('Ceiling:', np.ceil(arr))
print('Truncated:', np.trunc(arr))

Original array: [-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor: [-2. -2. -1.  0.  1.  1.  2.]
Ceiling: [-1. -1. -0.  1.  2.  2.  2.]
Truncated: [-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [101]:
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [102]:
arr=np.zeros(24)
a=np.arange("2023-12-19","2023-12-20",dtype='datetime64[h]')
print(a)
for i in range(len(arr)):
    for j in a:
        arr[i]=j
arr

['2023-12-19T00' '2023-12-19T01' '2023-12-19T02' '2023-12-19T03'
 '2023-12-19T04' '2023-12-19T05' '2023-12-19T06' '2023-12-19T07'
 '2023-12-19T08' '2023-12-19T09' '2023-12-19T10' '2023-12-19T11'
 '2023-12-19T12' '2023-12-19T13' '2023-12-19T14' '2023-12-19T15'
 '2023-12-19T16' '2023-12-19T17' '2023-12-19T18' '2023-12-19T19'
 '2023-12-19T20' '2023-12-19T21' '2023-12-19T22' '2023-12-19T23']


array([473063., 473063., 473063., 473063., 473063., 473063., 473063.,
       473063., 473063., 473063., 473063., 473063., 473063., 473063.,
       473063., 473063., 473063., 473063., 473063., 473063., 473063.,
       473063., 473063., 473063.])

### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [103]:
arr1 = np.array(['Python', 'PHP'])
arr2 = np.array([' Java', ' C++'])


d = []
for i in range(len(arr1)):
    d.append(arr1[i] +" "+arr2[i])
d

['Python  Java', 'PHP  C++']

## builtin function

In [104]:
arr1 = np.array(['Python', 'PHP'])
arr2 = np.array([' Java', ' C++'])

c = np.char.add(arr1, arr2)
c

array(['Python Java', 'PHP C++'], dtype='<U11')