# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [24]:
print(f" Version of Numpy {np.__version__}")
print(np.show_config())

 Version of Numpy 1.23.3
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', N

#### 3. Create a null vector of size 10 (★☆☆)

In [25]:
a =np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [27]:
item_size = a.itemsize *a.size
print(a.itemsize ,a.size)
item_size

8 10


80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [31]:
print(np.info(np.add))
print(np.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [32]:
n = np.zeros(10)
n[4] =1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [34]:
arr =np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [35]:
reverse = arr[::-1]
reverse

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [37]:
np.flip(arr)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [39]:
nine = np.arange(9).reshape(3,3)
nine

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [41]:
x = [1,2,0,0,4,0]
n = np.nonzero(x)
n

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [43]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [49]:
print(np.random.random((3,3,3)))


[[[0.50205742 0.49743308 0.54860762]
  [0.55608815 0.49291049 0.29668749]
  [0.93210315 0.91923389 0.95398154]]

 [[0.53915802 0.44152315 0.45413642]
  [0.17174449 0.14787766 0.34650413]
  [0.6972605  0.03032759 0.4844912 ]]

 [[0.736961   0.06014483 0.97529844]
  [0.6977159  0.80343792 0.31179525]
  [0.04193464 0.44627668 0.22502809]]]


array([1, 1, 1])

In [3]:
import numpy as np
np.random.randint((3,3,3))

array([1, 1, 1])

In [6]:
np.random.randint((1,10))

array([0, 1])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
metrix = np.random.random((10,10))


print(f"Metrix : {metrix} \n Minimum value {metrix.min()} \n Maximum value {metrix.max()}")




Metrix : [[0.94392372 0.83179219 0.02572405 0.07618225 0.95932938 0.0112042
  0.84358857 0.61242816 0.84898411 0.27105306]
 [0.5833495  0.259237   0.56759509 0.54020536 0.17735868 0.78336925
  0.974911   0.13038501 0.0145727  0.75665662]
 [0.48846083 0.20123565 0.41056204 0.02934604 0.57111043 0.19004601
  0.4564684  0.09967836 0.46574673 0.9630899 ]
 [0.61100986 0.83087111 0.90739983 0.78271859 0.16213605 0.90536177
  0.3445553  0.98433452 0.27278538 0.20336122]
 [0.43316644 0.33839254 0.14869621 0.16813472 0.9426638  0.95533068
  0.58828262 0.47852109 0.92369319 0.53738547]
 [0.41615021 0.02830384 0.60206661 0.28510123 0.44330023 0.41917177
  0.90428033 0.64808207 0.16011157 0.87543063]
 [0.63498279 0.18071007 0.19000854 0.38913323 0.81201003 0.01422391
  0.38989771 0.97325082 0.92791903 0.50096396]
 [0.93731241 0.38666038 0.84997709 0.08492347 0.98096685 0.95683997
  0.62357127 0.64227168 0.19451159 0.45731898]
 [0.6711888  0.59737617 0.80082875 0.082689   0.37019255 0.68791279
  0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
x = np.random.random(10)
print(x)
print(x.mean())

[0.77843125 0.058922   0.75642257 0.94628809 0.57660825 0.03759573
 0.91458629 0.28996514 0.55336661 0.38884163]
0.5301027572547211


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [54]:
x = np.ones((10,10))
print(x)
x[1:-1,1:-1] = 0
x


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [59]:
arr = np.arange(16).reshape(4,4)
print(arr)
np.pad(arr, pad_width=1, constant_values=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [48]:
x = np.zeros((4,4))
x[1:-1,1:-1] = 2
x

array([[0., 0., 0., 0.],
       [0., 2., 2., 0.],
       [0., 2., 2., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [52]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


Let's go through each line one by one:

1. `print(0 * np.nan)`

   This prints the result of multiplying 0 by NaN (Not a Number), which results in NaN. In mathematical operations involving NaN, the result is typically NaN.

2. `print(np.nan == np.nan)`

   This prints `False`. In NumPy and many other programming environments, NaN is considered not equal to itself. This behavior is a result of the IEEE floating-point standard.

3. `print(np.inf > np.nan)`

   This prints `False`. Infinity (`np.inf`) is considered greater than any finite number, but it is not comparable to NaN. In comparisons involving NaN, the result is typically considered undefined or false.

4. `print(np.nan - np.nan)`

   This prints `NaN`. Any arithmetic operation involving NaN typically results in NaN.

5. `print(np.nan in set([np.nan]))`

   This prints `True`. Although NaN is not equal to itself in a direct equality check (`==`), it is considered equal when using the `in` operator with a set or list.

6. `print(0.3 == 3 * 0.1)`

   This prints `False`. Due to the way floating-point numbers are represented in computers, the result of `3 * 0.1` is not exactly equal to `0.3`. It's a common issue with floating-point arithmetic, and it's recommended to use methods like `np.isclose()` for floating-point equality comparisons.


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [62]:
arr = np.array([1, 2, 3, 4])
d = np.diag(arr, k=-1)
d

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [68]:
a = np.zeros(64).reshape(8,8)
a[1::2 , ::2] = 1
a[::2, 1::2] = 1
a


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [69]:
print(a[1::2 , ::2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [70]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [3]:
import numpy as np
np.info(np.tile)

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [72]:
chess = np.tile( np.array([[0,1],[1,0]]), (4,4))
chess

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [7]:
x = np.random.random(25).reshape(5,5)
normalize = (x- np.mean(x))/ np.std(x)
normalize

array([[ 0.4506328 ,  0.37030671,  0.22681364, -1.0421874 , -0.2596549 ],
       [ 0.75778045,  0.95554279, -2.44846992, -0.7649257 , -1.97121077],
       [-1.52615178,  0.7851207 ,  0.39307791, -1.54465983,  0.58348704],
       [ 1.25210482,  0.09012861,  0.16972337,  0.772334  ,  0.76401357],
       [ 1.12319033,  0.64079769,  0.93153207, -0.57691579, -0.13241042]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [11]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
# Create an array with the custom dtype
color_array = np.array([(255, 0, 0, 255),   # Red with full opacity
                       (0, 255, 0, 128),    # Green with semi-transparency
                       (0, 0, 255, 0)],     # Blue with full transparency
                      dtype=color)
type(color_array)

numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [14]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
r = np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [16]:
r = a@b
r

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [7]:
z = np.arange(14)

z[(z>3 ) & (z < 8 )] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In the NumPy version, the result is different from the built-in sum because NumPy's sum function treats the second argument as the axis along which the sum is calculated. In this case, -1 represents the last axis. 

In [10]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Let's analyze each expression:

1. `Z**Z`: This expression raises each element of the vector `Z` to the power of itself. It is legal in Python.

2. `2 << Z >> 2`: This expression performs bitwise left shift and right shift operations. It is legal.

3. `Z <- Z`: This expression checks if each element in `Z` is less than the negation of itself. It is legal.

4. `1j*Z`: This expression multiplies each element of the vector `Z` by the imaginary unit `1j`. It is legal.

5. `Z/1/1`: This expression divides each element of the vector `Z` by 1 twice. It is legal.

6. `Z<Z>Z`: This expression is not legal in Python. The reason is that the chained comparison `Z < Z < Z` is syntactically invalid. You need to use logical operators explicitly, such as `Z < Z and Z < Z`.

Here's a summary:

- Legal:
  1. `Z**Z`
  2. `2 << Z >> 2`
  3. `Z <- Z`
  4. `1j*Z`
  5. `Z/1/1`

- Not Legal:
  6. `Z<Z>Z` (Use logical operators to express the comparison correctly, like `Z < Z and Z < Z`)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

Let's break down each of these expressions:

1. `np.array(0) / np.array(0)`:
   - This expression involves dividing two NumPy arrays, both of which contain a single element with the value `0`.
   - In NumPy, division by zero doesn't raise an error; instead, it produces a special value called "nan" (not a number).
   - The result of `np.array(0) / np.array(0)` is `nan`.

2. `np.array(0) // np.array(0)`:
   - Similar to the previous case, this expression involves floor division (`//`) of two NumPy arrays, both containing the value `0`.
   - Just like regular division, floor division by zero in NumPy doesn't raise an error; instead, it results in `0`.
   - The result of `np.array(0) // np.array(0)` is `0`.

3. `np.array([np.nan]).astype(int).astype(float)`:
   - Here, you have a NumPy array with a single element containing `np.nan` (not a number).
   - The `.astype(int)` converts the `np.nan` to an integer, resulting in `0` (conversion of `nan` to integer gives `0`).
   - The subsequent `.astype(float)` converts the integer `0` back to a float, resulting in `0.0`.
   - So, the final result is an array with a single element, which is a floating-point number: `array([0.])`.


In [12]:
np.array(0) / np.array(0)


C:\Users\A\AppData\Local\Temp\ipykernel_9008\3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [13]:
np.array(0) // np.array(0)

C:\Users\A\AppData\Local\Temp\ipykernel_9008\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [16]:

x = np.array([np.nan]).astype(int).astype(float)
x

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [18]:
Z = np.random.uniform(-10,+10,10)
print(z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13]
[-7.  5. -2.  1. 10.  4.  3. -8. -7.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [23]:
a = np.array([1,2,3,4,3,2,5,57,78])
b = np.array([1,3,4,5])

np.intersect1d(a,b)

array([1, 3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [24]:
np.seterr(all = "ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [25]:
z = np.ones(1)/0
z

array([inf])

In [28]:
_ = np.seterr(**defaults)

NameError: name 'defaults' is not defined

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

`np.sqrt(-1)` results in a complex number (`nan + 1j`) due to the use of the NumPy complex number handling, while `np.emath.sqrt(-1)` returns a complex number (`1j`) using the enhanced mathematical functions in NumPy's `emath` module.

In [29]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
from datetime import datetime , timedelta

today = np.datetime64('today')
print(today)
tomorrow = np.datetime64('today') +1
print(tomorrow)
yesterday = np.datetime64('today') -1
print(yesterday)

2023-12-20
2023-12-21
2023-12-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
np.arange('2016-07' , '2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [80]:
# a = np.arange(10)
# b = np.arange(10,20)
import numpy as np
x = np.ones(3)*1
y = np.ones(3)*2
print(x,y)
np.sum(x ,y , out= x)

[1. 1. 1.] [2. 2. 2.]


TypeError: only integer scalar arrays can be converted to a scalar index

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [88]:
a = np.random.random(7)*np.arange(7)
print(a)
print(np.floor(a).astype(int))
print(a.astype(int))
print(np.trunc(a).astype(int))
np.int_(a)


[0.         0.43218539 0.27027362 1.85546302 2.79802538 4.97676306
 4.71166304]
[0 0 0 1 2 4 4]
[0 0 0 1 2 4 4]
[0 0 0 1 2 4 4]


array([0, 0, 0, 1, 2, 4, 4])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [46]:
x = np.zeros((5,5))
x +=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [49]:
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [52]:
def genrater():
    for i in range(10):
        yield i

np.fromiter(genrater(), dtype="int")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

NumPy’s fromiter() function is a handy tool for creating a NumPy array from an iterable object. This iterable can be any Python object that provides elements one at a time. The function is especially useful when you need to convert data from a custom data source, like a file or generator, into a NumPy array for further analysis.

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [56]:
np.linspace(0,1 ,num=12 , endpoint=False)[1:-1]

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [61]:
z =np.sort(np.random.random(10))
z

array([0.12442701, 0.13167948, 0.22218396, 0.25319988, 0.49808459,
       0.54477781, 0.59847372, 0.64635767, 0.96481584, 0.97942298])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [62]:
np.add.reduce(z)

4.963422934443157

In [63]:
import functools as f

f.reduce(np.add,z)

4.963422934443157

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [66]:
A = np.random.random(10)
B = np.random.random(10)

np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [70]:
a = np.ones(10)
print(a)
a[2]=3
print(a)
a.flags.writeable = False
a[2]=3
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 3. 1. 1. 1. 1. 1. 1. 1.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [71]:
s = np.random.random((10,2))
s

array([[0.52068465, 0.63190694],
       [0.25932635, 0.68679365],
       [0.07740038, 0.69377183],
       [0.97926079, 0.49050166],
       [0.913666  , 0.26950365],
       [0.53474035, 0.82421813],
       [0.53141547, 0.57151908],
       [0.94223598, 0.98442658],
       [0.73901168, 0.60164245],
       [0.61526347, 0.11620545]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

- "np.max()" returns the maximum value in an array.
- "np.argmax()" returns the index of the first maximum value in an array. 

In [79]:
s = np.random.random(10)
s[s.argmax()]= 0

s

array([0.22929971, 0.09706844, 0.49297877, 0.6311734 , 0.13808912,
       0.        , 0.51744939, 0.46466275, 0.24508769, 0.5231886 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [90]:

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [89]:
x = [0 ,1]
y = [0,1]

np.meshgrid(x,y)

[array([[0, 1],
        [0, 1]]),
 array([[0, 0],
        [1, 1]])]

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [91]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [94]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [95]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [93]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
91.60646540838667
92


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)